name: build-test-deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.4.0

    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '18.12.0'
    
    - name: Install pnpm globally
      run: npm i -g pnpm
      
    - name: Install dependencies
      run: pnpm i
      
    - name: Lint
      run: pnpm run lint
      
    - name: Test
      run: pnpm run test-ci
  
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.4.0

    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '18.12.0'
    
    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
