name: build-and-deploy

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.4.0

    - uses: actions/setup-node@v3.6.0
      with:
        node-version: '16.18.0'
    
    - name: Install pnpm globally
      run: npm i -g pnpm
      
    - name: Install dependencies
      run: pnpm i
      
    - name: Lint
      run: pnpm run lint
      
    - name: Test
      run: pnpm run test-ci
